MasterCruelty/robbot

- help.json
- modules/covid.py
It's impossible to see current date data of vaccine. 
So the function ```vaccinedate(client,message,query)``` returns now data of a specific date and/or region requested.
> Modified vaccine function

- help.json
- modules/covid.py
- utils/utility.py
Fixed a little bug inside ```vaccinedate(client,message,query)``` and then created two new functions:
```vaccinepoints``` and ```check_vaccine_function``` ✨ 
The first one shows list of somministration points of requested province.
The second one just checks the query and decide which vaccine function has to be executed
> Vaccine function update

- utils/sysfunctions.py
```/getmessage``` works again
🐛 fixed
> :bug: fix /getmessage

- modules/covid.py
Deleted every references to over80 because it doesn't exists anymore in the external json file somministrazioni-vaccini-latest
> :bug: Fix covid.py closes #17

- modules/covid.py
- modules/gmaps.py
Handled a few exceptions in ```covid.py``` and ```gmaps.py```.
Added some documentation and comments in ```gmaps.py```.
> 🔧 Update covid and gmaps

- help.json
- modules/reminder.py
- modules/wiki.py
Handled an exception in ```wiki.py``` 
Improved ```setTime(client,message,query)``` function.
> 🔧 Update wiki.py and reminder.py

- utils/dbfunctions.py
- utils/dbtables.py
Deleted Admin and SuperAdmin table and added two boolean fields in User table for admin and superadmin :rocket:
This close #16
> :rocket: Database improved

- modules/wiki.py
Fixed logic error in ```wiki.py``` and improved the creation of Wikipedia links.
This closes #22
> Fix and improved wiki 

- utils/dbfunctions.py
- utils/dbtables.py
- utils/utility.py
Created a new table ```Stats``` and functions to create a new command ```/mystat``` which say how many times you used a command.
> New feature: /mystat

- modules/reminder.py
- utils/dbfunctions.py
- Fixed reminder when <code>result == 0</code> #27 
- Improved <code>/mystat</code> command #26 
- Improved <code>/listrobuser</code> command #28
> Solving #26, #27 and #28

- modules/atm_feature.py
- utils/dbfunctions.py
- utils/utility.py
- Closed #10 
- Little fix to <code>dbfunctions.py</code>
> Fix and "solved" #10

- modules/atm_feature.py
- modules/covid.py
- modules/reminder.py
- modules/weather.py
- utils/dbfunctions.py
- utils/sysfunctions.py
- utils/utility.py
Same changes as done here: https://github.com/MasterCruelty/my-tg-app/pull/31
> 🚀 ♻️ Refactor

- utils/dbfunctions.py
Fixed condition in <code>list_user</code> function
> :bug: Fix /listrobuser

- modules/covid.py
- utils/sysfunctions.py
Fixed /helprob command which close #40 and added the additional info in <code>/vaccine</code> which close #41
> Solved #40 and #41

- help.json
- modules/reminder.py
I just changed the split parameter from <code>/</code> to <code>;</code>
> Update reminder feature

- modules/atm_feature.py
Added a couple of  headers to bypass 403 error.
It's not enough but it works for a while.
It should close #46 
WIP
> :wrench: Try fix 403 

- modules/atm_feature.py
Error message if no stops found
> :wrench: Handle exception

- modules/covid.py
- modules/reminder.py
- modules/wiki.py
- utils/controller.py
- utils/sysfunctions.py
Refactored a few imports
```ruby
import utils.get_config as ugc
import utils.dbfunctions as udb
import utils.controller as uct
```
> ♻️ Refactor some import

- modules/weather.py
Fix an if condition in <code>/weather</code> command
> 🐛  Fix condition

- utils/dbfunctions.py
Fixed a query. Basically an admin user could launch super admin commands.
> 🔒  Fix query

- help.json
- modules/covid.py
Used Pandas to manage csv data of vaccines. It's now more efficient than read a huge json file.
This will close #45
>  🚀 Improved /vaccine

- app.py
- utils/controller.py
- utils/sysfunctions.py
* /weathermap moved to admin commands
* Updated help message 
* Updated arguments on admin functions
> Moved /weathermap and Updated help message

- .gitignore
- help.json
- modules/weather.py
- utils/controller.py
- utils/get_config.py
- utils/sysfunctions.py
* Created  <code>/weathersat</code> function. 
* Updated <code>/playlotto</code>.
> 🚀 /weathersat 

- modules/weather.py
Not found images were sended anyway as empty gif, now it's fixed
> 🐛 Update sat24_map function

- README.md
- config-example.json
- help.json
- modules/openai.py
- utils/controller.py
- utils/sysfunctions.py
* Created a command that use OpenAI API 
* Update <code>help.json</code>
> OpenAI command

- app.py
- modules/covid.py
- modules/gmaps.py
- modules/wiki.py
- utils/controller.py
- utils/get_config.py
- utils/sysfunctions.py
Just removed a lot of <code>import time</code> not used in the actual source code
> :recycle: Refactor: removed useless import lines

- modules/urban.py
- modules/wiki.py
- utils/controller.py
- utils/sysfunctions.py
* Developer a new command: <code>/urban</code> which fetch data from Urban Dictionary
* Details for usage in <code>help.json</code>
This will close #60
> :rocket: /urban command

- modules/wiki.py
auto_suggest works bad, just disabled
> ♻️ auto-suggest disabled

- modules/atm_feature.py
Disabled ssl certificate verification to bypass SSLError in <code>atm_feature.py</code>
> 🚀 Fix SSLError 

- app.py
- help.json
- modules/wiki.py
- utils/get_config.py
- utils/sysfunctions.py
Until now it was running on <code>pyrogram version 1.2.6</code>.
I updated to the last version <code>2.*</code>
Fixed several changes between the versions.
> 🚀 Update of Pyrogram 

- utils/dbfunctions.py
> :bug: Fix json

- utils/sysfunctions.py
> :bug: Handle exception

- modules/lyrics.py
- modules/urban.py
- modules/weather.py
* Added InlineKeyboardButtons to solve the problem of long messages. This solves #15 and then #74.
* The functions are a first version, they works as they are but they will be improved in the future with a back button instead of only a next one for the pages.
> 🚀 ⌨️ Add inlineKeyboard buttons

- utils/sysfunctions.py
Handled exception in /poll command, didnt caught and it's related to #77
> :recycle: Handle error

- help.json
- modules/tper.py
You can now request info for a specific line in a stop by adding the line number after the stop code
> Line filter in /tper

- modules/gmaps.py
More info on location response; Done 1 task in #76
> 🗺️ Update /map

- help.json
- modules/gmaps.py
Added option <code>-i</code> in /map command to show only info about the place without map
> Add option in /map

- modules/covid.py
Adjust the new field's names as read in the [Changelog](https://github.com/italia/covid19-opendata-vaccini/blob/master/Changelog.md) of the repository of Italian vaccine data.
This solves #92
> 🔧 Fix /vaccine

- help.json
- modules/pistekart.py
- utils/controller.py
<code>/piste</code> and <code>/infopista</code> commands.
These commands fetch data about Italian gokart tracks as mentioned in #102.
> 🚀 pistekart scraping

- .gitignore
- README.md
- app.py
- help.json
- modules/pistekart.py
- modules/trivial.py
- utils/controller.py
- utils/dbfunctions.py
- utils/dbtables.py
- utils/get_config.py
* Created <code>/trivial</code> feature. All tasks done in #75 
* Added new db functions. 3rd task of #53 
* In progress 1st task of #53
> 🚀 /Trivial feature and db update

- help.json
- modules/weather.py
- utils/dbfunctions.py
* Adjusted the leaderboard by category in `/trivial`
* Refactored `/weathersat` and `/weathermap` to solve #104
> ♻️ Refactor

- utils/dbfunctions.py
* Adjust `/trivial` leaderbord 
* Refactor show_stats
> :recycle: Refactor

- help.json
- utils/dbfunctions.py
* Refactor leaderboard function.
* Refactor show_stats function.
* Update help.json
> ♻️ Refactor dbfunctions.py

- help.json
- modules/gmaps.py
- modules/ingv.py
- utils/controller.py
> 🚀 /eq command 

- README.md
- help.json
- modules/openai.py
- utils/controller.py
- utils/dbfunctions.py
- utils/dbtables.py
* davinci003 instead of davinci001.
* Add credit system for users.
This solves #97
> 🚀 Update openai feature 

- README.md
- utils/controller.py
- utils/sysfunctions.py
* Add <code> /restart </code> command which restart the bot directly in Telegram. This solves #110
> 🔧 /restart command

- help.json
- modules/videodl.py
- utils/controller.py
- utils/get_config.py
* Add <code>/yt</code> command which download a youtube feature.
* Add <code>sendVideo</code> function in get_config.py.
> 🚀  YouTube download feature

- README.md
- help.json
- modules/animals.py
- modules/latex.py
- utils/controller.py
- utils/get_config.py
* Add <code>/rabbit</code> command which sends rabbit images.
* Add <code>/bird</code> command which sends bird images.
* Add <code>/latex</code> command which sends compiled LaTeX using free api.
> 🚀 a few features

- app.py
- utils/controller.py
* Updated <code>visualizza</code> function to send a message to super admin chat to log the arrived messages and errors. This will close #125
> ♻️ 🚀 Logging messages and errors directly in Telegram

- README.md
- help.json
- modules/passport.py
- utils/controller.py
* Add <code>/passport</code> command which give basic info about a selected passport
> 🚀 Add /passport command

- modules/atm_feature.py
- modules/gmaps.py
- modules/latex.py
- modules/pistekart.py
- modules/trivial.py
- modules/viaggiatreno.py
- modules/videodl.py
- modules/weather.py
- modules/wiki.py
- utils/dbfunctions.py
- utils/sysfunctions.py
* Update of <code>/mystat</code> which now do also a bar plot if you type <code>-bar</code> option.
* Fixed colour palette improving the code. Thanks @archetipico for support.
* WIP for other fix/improvements I don't merge now. I want to close #133 and #129 here.
> ♻️ 🚀 Refactor update

- README.md
- help.json
- modules/weatherextreme.py
- utils/controller.py
- utils/sysfunctions.py
* <code>/poll</code> have now the possibility of multiple answers.
* <code>/extremeforecast</code> command to get data about extreme event forecast in Italian regional zone or specific municipality.
> Poll update and maybe something else

- modules/weatherextreme.py
* Added information detail about the zone linked to the zone-code
> :wrench: add details about zone in /extremeforecast

- help.json
- modules/space.py
- utils/controller.py
* Added a command <code>/apod</code> that fetch the Astrony Picture of the day from Nasa API.
This solves #143
> Astronomy Picture of the day

- help.json
- modules/bgg.py
- modules/space.py
- utils/controller.py
* Handled case when <code>/apod</code> has a caption longer than the maximum of a Telegram message.
* Building <code>/bgg</code> and <code>/bggsearch</code>
This should close #145 and #137
> :wrench: :rocket: Fixing /apod and releasing more

- modules/videodl.py
- utils/get_config.py
* Updated pytube, #148 solved for now.
* Added two progress messages in <code>/yt</code>.
* Handles an exception in <code>get_username</code> in <code>get_config.py</code>
> :recycle: added progress messages

- README.md
- config-example.json
- modules/atm_feature.py
> 🔓 🚀 Fix 403 on /atm

- modules/atm_feature.py
- modules/flight.py
* Refactor <code>get_time_table</code>
* Fix <code>/aiport</code> to work also with airport without a rating.
> ♻️ 🐛 Refactor

- modules/openai.py
> fix :bug: openai feature

- modules/atm_feature.py
> end of service /atm

- help.json
- modules/wiki.py
* added another option "-s" to get a specific section of a wiki page.
* /wiki standard command now show also all the available sections of the page.
> 🔧 solving wiki section update #165

- README.md
- config-example.json
- modules/animals.py
- modules/atm_feature.py
* Fixed <code>/rabbit</code> & <code>/bird </code> by setting new api url with access key.
* Fixed <code> /atm</code> by retrieving new api url and new headers. I hope the cookie won't refresh often.
> 🔧 🚀 🐛 Fix /bird;/rabbit;/atm
